/* The following code was generated by JFlex 1.6.1 */

//codigo de usuario
//paquetes e importaciones
package Analisis.haskell;
import java_cup.runtime.*;
import Reportes.*;

//opciones y declaraciones

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analisis/haskell/LexicoHaskell.jflex</tt>
 */
public class LexicoHaskell implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    54, 54, 54, 54, 54, 54, 54, 54, 54, 11,  4,  6,  7,  5, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    11, 43,  9, 54, 44, 54, 39,  3, 49, 50, 35, 33, 51, 34, 54, 36, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 52, 53, 40, 41, 42, 54, 
    54, 13,  2, 12, 21, 17, 32, 30, 31, 24,  2,  2, 14, 22, 25, 28, 
    27, 37, 16, 20, 18, 15, 29,  2, 26,  2,  2, 47, 10, 48, 54,  2, 
    54, 13,  2, 12, 21, 17, 32, 30, 31, 24,  2,  2, 14, 22, 25, 28, 
    27, 37, 16, 20, 18, 15, 29,  2, 26,  2,  2, 45, 38, 46, 54, 54, 
    54, 54, 54, 54, 54,  6, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 
    54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\3\1\5"+
    "\1\3\6\2\1\0\3\2\1\0\2\2\1\6\1\7"+
    "\1\10\1\11\2\3\1\12\1\13\1\14\1\3\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\5\0\1\27\1\0\1\2\1\0\6\2\1\0"+
    "\3\2\1\0\1\2\1\0\1\30\1\2\1\30\2\2"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\3\0\1\27\1\2\1\0\1\2\2\42\1\43"+
    "\2\2\1\0\1\2\1\44\1\2\1\0\1\45\1\2"+
    "\1\45\1\2\1\0\1\2\1\46\2\47\1\0\1\2"+
    "\1\50\1\2\3\0\1\2\2\51\2\2\2\52\1\53"+
    "\2\54\1\55\2\56\2\57\1\2\1\0\1\60\1\61"+
    "\4\2\1\62\1\2\1\63\2\64\2\2\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0113"+
    "\0\u0113\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u0113\0\u0113\0\u0113\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596"+
    "\0\u05cd\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113"+
    "\0\u0113\0\u0113\0\u0113\0\u0604\0\u063b\0\u0672\0\u06a9\0\u0181"+
    "\0\u0113\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0113\0\u0a50\0\245\0\u0a87\0\u0abe\0\u0113\0\u0113"+
    "\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0af5"+
    "\0\u0b2c\0\u0b63\0\u0181\0\u0b9a\0\u0bd1\0\u0c08\0\u0113\0\245"+
    "\0\245\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\245\0\u0d1b\0\u0d52"+
    "\0\u0113\0\u0d89\0\245\0\u0dc0\0\u0df7\0\u0e2e\0\245\0\u0113"+
    "\0\245\0\u0e65\0\u0e9c\0\245\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78"+
    "\0\u0faf\0\u0113\0\245\0\u0fe6\0\u101d\0\u0113\0\245\0\245"+
    "\0\u0113\0\245\0\245\0\u0113\0\245\0\u0113\0\245\0\u1054"+
    "\0\u108b\0\u0113\0\u0113\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u0113"+
    "\0\u119e\0\245\0\u0113\0\245\0\u11d5\0\u120c\0\245\0\245";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\0\1\12\1\10\1\11\1\13\1\14\1\15\1\4"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\2\4\1\27\5\4\1\30\1\31\1\32\1\33"+
    "\1\4\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\10\1\0\7\10\1\0\12\10\1\0\3\10"+
    "\1\0\37\10\1\0\1\3\66\0\2\4\11\0\7\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\21\0\4\54"+
    "\5\0\12\54\2\55\1\54\1\56\4\54\1\57\33\54"+
    "\73\0\1\11\62\0\11\60\1\61\1\62\54\60\1\0"+
    "\2\4\11\0\1\4\1\63\5\4\1\0\3\4\1\0"+
    "\11\4\4\0\1\4\22\0\2\4\11\0\7\4\1\64"+
    "\1\65\2\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\5\4\1\66\1\4\1\0\3\4\1\0\11\4"+
    "\4\0\1\4\22\0\2\4\11\0\5\4\1\67\1\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\2\4\1\70\4\4\1\0\3\4\1\0\1\4"+
    "\1\71\7\4\4\0\1\4\22\0\2\4\11\0\7\4"+
    "\1\0\3\4\1\0\7\4\1\72\1\4\4\0\1\4"+
    "\40\0\1\73\50\0\2\4\11\0\3\4\1\74\3\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\5\4\1\75\1\4\1\0\3\4\1\0\11\4"+
    "\4\0\1\4\22\0\2\4\11\0\1\4\1\76\5\4"+
    "\1\0\3\4\1\77\1\100\10\4\4\0\1\4\47\0"+
    "\1\101\11\0\1\102\27\0\2\4\11\0\7\4\1\0"+
    "\2\4\1\103\1\0\10\4\1\104\4\0\1\4\22\0"+
    "\2\4\11\0\1\4\1\105\2\4\1\106\2\4\1\0"+
    "\3\4\1\0\11\4\4\0\1\4\62\0\1\107\73\0"+
    "\1\110\67\0\1\111\70\0\1\112\66\0\1\113\66\0"+
    "\1\114\66\0\1\115\1\0\1\116\16\0\1\117\66\0"+
    "\1\117\41\0\1\120\24\0\1\117\30\0\1\121\35\0"+
    "\1\117\30\0\1\122\32\0\11\60\1\123\1\62\54\60"+
    "\1\0\2\4\11\0\2\4\1\124\4\4\1\125\1\126"+
    "\2\4\1\0\11\4\4\0\1\4\35\0\1\127\53\0"+
    "\2\4\11\0\1\130\6\4\1\0\3\4\1\0\11\4"+
    "\4\0\1\4\22\0\2\4\11\0\6\4\1\131\1\0"+
    "\3\4\1\0\1\4\1\132\7\4\4\0\1\4\22\0"+
    "\2\4\11\0\7\4\1\0\3\4\1\0\5\4\1\133"+
    "\3\4\4\0\1\4\22\0\2\4\11\0\7\4\1\134"+
    "\1\135\2\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\7\4\1\0\1\4\1\136\1\4\1\0\11\4"+
    "\4\0\1\4\22\0\2\4\11\0\5\4\1\137\1\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\35\0\1\140"+
    "\11\0\1\141\41\0\2\4\11\0\1\142\6\4\1\0"+
    "\2\4\1\143\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\1\144\6\4\1\145\1\146\2\4\1\0\11\4"+
    "\4\0\1\4\22\0\2\4\11\0\7\4\1\0\3\4"+
    "\1\0\2\4\1\147\6\4\4\0\1\4\52\0\1\150"+
    "\36\0\2\4\11\0\7\4\1\0\3\4\1\0\1\4"+
    "\1\151\7\4\4\0\1\4\54\0\1\152\34\0\2\4"+
    "\11\0\7\4\1\0\3\4\1\0\3\4\1\153\5\4"+
    "\4\0\1\4\22\0\2\4\11\0\4\4\1\154\2\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\7\4\1\0\3\4\1\0\4\4\1\155\4\4"+
    "\4\0\1\4\41\0\1\156\73\0\1\157\63\0\1\160"+
    "\45\0\2\4\11\0\1\161\6\4\1\0\3\4\1\0"+
    "\11\4\4\0\1\4\42\0\1\162\46\0\2\4\11\0"+
    "\5\4\1\163\1\4\1\0\3\4\1\0\11\4\4\0"+
    "\1\4\22\0\2\4\11\0\7\4\1\0\3\4\1\0"+
    "\6\4\1\164\2\4\4\0\1\4\22\0\2\4\11\0"+
    "\5\4\1\165\1\4\1\0\3\4\1\0\11\4\4\0"+
    "\1\4\42\0\1\166\46\0\2\4\11\0\5\4\1\167"+
    "\1\4\1\0\3\4\1\0\11\4\4\0\1\4\22\0"+
    "\2\4\11\0\7\4\1\0\3\4\1\0\1\4\1\170"+
    "\7\4\4\0\1\4\35\0\1\171\53\0\2\4\11\0"+
    "\1\172\6\4\1\0\3\4\1\0\11\4\4\0\1\4"+
    "\22\0\2\4\11\0\1\173\6\4\1\0\3\4\1\0"+
    "\11\4\4\0\1\4\35\0\1\174\53\0\2\4\11\0"+
    "\1\175\6\4\1\0\3\4\1\0\11\4\4\0\1\4"+
    "\41\0\1\176\47\0\2\4\11\0\4\4\1\177\2\4"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\7\4\1\0\1\4\1\200\1\4\1\0\11\4"+
    "\4\0\1\4\43\0\1\201\47\0\1\202\66\0\1\203"+
    "\64\0\2\4\11\0\3\4\1\204\3\4\1\0\3\4"+
    "\1\0\11\4\4\0\1\4\22\0\2\4\11\0\6\4"+
    "\1\205\1\0\3\4\1\0\11\4\4\0\1\4\22\0"+
    "\2\4\11\0\4\4\1\206\2\4\1\0\3\4\1\0"+
    "\11\4\4\0\1\4\22\0\2\4\11\0\3\4\1\207"+
    "\3\4\1\0\3\4\1\0\11\4\4\0\1\4\24\0"+
    "\1\210\64\0\2\4\11\0\2\4\1\211\4\4\1\0"+
    "\3\4\1\0\11\4\4\0\1\4\22\0\2\4\11\0"+
    "\7\4\1\0\3\4\1\0\7\4\1\212\1\4\4\0"+
    "\1\4\22\0\2\4\11\0\7\4\1\213\1\214\2\4"+
    "\1\0\11\4\4\0\1\4\22\0\2\4\11\0\1\215"+
    "\6\4\1\0\3\4\1\0\11\4\4\0\1\4\22\0"+
    "\2\4\11\0\1\4\1\216\5\4\1\0\3\4\1\0"+
    "\11\4\4\0\1\4\22\0\2\4\11\0\6\4\1\217"+
    "\1\0\3\4\1\0\11\4\4\0\1\4\22\0\2\4"+
    "\11\0\4\4\1\220\2\4\1\0\3\4\1\0\11\4"+
    "\4\0\1\4\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4675];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\3\1\1\11\1\1\2\11\7\1\1\0\3\1"+
    "\1\0\3\1\3\11\6\1\12\11\5\0\1\11\1\0"+
    "\1\1\1\0\6\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\11\4\1\11\11\3\0\2\1\1\0\1\1\1\11"+
    "\4\1\1\0\3\1\1\0\1\11\3\1\1\0\2\1"+
    "\1\11\1\1\1\0\3\1\3\0\1\1\1\11\3\1"+
    "\1\11\2\1\1\11\2\1\1\11\1\1\1\11\2\1"+
    "\1\0\2\11\4\1\1\11\2\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Codigo de usuario en sitaxis java por ejemplo una variable global
    StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoHaskell(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(symsH.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(symsH.numero, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 2: 
            { return new Symbol(symsH.iden, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 3: 
            { ErroresHaskell.agregarError("Error Lexico", "El caracter [" + yytext() + "] no es valido", yyline, yycolumn);
            }
          case 57: break;
          case 4: 
            { return new Symbol(symsH.enter, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 5: 
            { /* ignore */
            }
          case 59: break;
          case 6: 
            { return new Symbol(symsH.mas, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 7: 
            { return new Symbol(symsH.menos, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 8: 
            { return new Symbol(symsH.por, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 9: 
            { return new Symbol(symsH.dividido, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 10: 
            { return new Symbol(symsH.menor, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 11: 
            { return new Symbol(symsH.igual, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 12: 
            { return new Symbol(symsH.mayor, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 13: 
            { return new Symbol(symsH.dolar, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 14: 
            { return new Symbol(symsH.allave, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 15: 
            { return new Symbol(symsH.cllave, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 16: 
            { return new Symbol(symsH.acorchete, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 17: 
            { return new Symbol(symsH.ccorchete, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 18: 
            { return new Symbol(symsH.aparentesis, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 19: 
            { return new Symbol(symsH.cparentesis, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 20: 
            { return new Symbol(symsH.coma, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 21: 
            { return new Symbol(symsH.dospuntos, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 22: 
            { return new Symbol(symsH.puntoycoma, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 23: 
            { return new Symbol(symsH.cadena, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 24: 
            { return new Symbol(symsH._if, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 25: 
            { return new Symbol(symsH.masmas, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 26: 
            { return new Symbol(symsH.or, yycolumn, yyline, yytext());
            }
          case 80: break;
          case 27: 
            { return new Symbol(symsH.and, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 28: 
            { return new Symbol(symsH.menorigual, yycolumn, yyline, yytext());
            }
          case 82: break;
          case 29: 
            { return new Symbol(symsH.igualigual, yycolumn, yyline, yytext());
            }
          case 83: break;
          case 30: 
            { return new Symbol(symsH.mayorigual, yycolumn, yyline, yytext());
            }
          case 84: break;
          case 31: 
            { return new Symbol(symsH.diferente, yycolumn, yyline, yytext());
            }
          case 85: break;
          case 32: 
            { return new Symbol(symsH.poslista, yycolumn, yyline, yytext());
            }
          case 86: break;
          case 33: 
            { return new Symbol(symsH.caracter, yycolumn, yyline, yytext());
            }
          case 87: break;
          case 34: 
            { return new Symbol(symsH.asc, yycolumn, yyline, yytext());
            }
          case 88: break;
          case 35: 
            { return new Symbol(symsH.let, yycolumn, yyline, yytext());
            }
          case 89: break;
          case 36: 
            { return new Symbol(symsH._end, yycolumn, yyline, yytext());
            }
          case 90: break;
          case 37: 
            { return new Symbol(symsH.sum, yycolumn, yyline, yytext());
            }
          case 91: break;
          case 38: 
            { return new Symbol(symsH.max, yycolumn, yyline, yytext());
            }
          case 92: break;
          case 39: 
            { return new Symbol(symsH.min, yycolumn, yyline, yytext());
            }
          case 93: break;
          case 40: 
            { return new Symbol(symsH.par, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 41: 
            { return new Symbol(symsH._case, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 42: 
            { return new Symbol(symsH._else, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 43: 
            { return new Symbol(symsH._then, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 44: 
            { return new Symbol(symsH.succ, yycolumn, yyline, yytext());
            }
          case 98: break;
          case 45: 
            { return new Symbol(symsH.decc, yycolumn, yyline, yytext());
            }
          case 99: break;
          case 46: 
            { return new Symbol(symsH.desc, yycolumn, yyline, yytext());
            }
          case 100: break;
          case 47: 
            { return new Symbol(symsH.impr, yycolumn, yyline, yytext());
            }
          case 101: break;
          case 48: 
            { return new Symbol(symsH.mod, yycolumn, yyline, yytext());
            }
          case 102: break;
          case 49: 
            { return new Symbol(symsH.pot, yycolumn, yyline, yytext());
            }
          case 103: break;
          case 50: 
            { return new Symbol(symsH.sqrt, yycolumn, yyline, yytext());
            }
          case 104: break;
          case 51: 
            { return new Symbol(symsH.length, yycolumn, yyline, yytext());
            }
          case 105: break;
          case 52: 
            { return new Symbol(symsH.revers, yycolumn, yyline, yytext());
            }
          case 106: break;
          case 53: 
            { return new Symbol(symsH.product, yycolumn, yyline, yytext());
            }
          case 107: break;
          case 54: 
            { return new Symbol(symsH.calcular, yycolumn, yyline, yytext());
            }
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
