package ide;
public class Const {
    public static final String 
            calcular = "calcular",
            let = "let",
            succ = "succ",
            decc = "decc",
            min = "min",
            max = "max",
            sum = "sum",
            product = "product",
            revers = "revers",
            impr = "impr",
            par = "par",
            asc = "asc",
            desc = "desc",
            length = "length",
            si = "si",
            sino = "sino",
            
            mas = "+",
            menos = "-",
            por = "*",
            dividido = "/",
            mod = "mod",
            sqrt = "sqrt",
            pot = "pot",
            or = "||",
            and = "&&",
            menor = "<",
            mayor = ">",
            menorigual = "<=",
            mayorigual = ">=",
            diferente = "!=",
            igualigual = "==",
            igual = "=",
            dolar = "$",
            porcentaje = "%",
            masmas = "++";
    
    public static final String 
            publico = "publico",
            privado = "privado",
            protegido = "protegido",
            asignacion = "asignacion",
            declaracion = "declaracion",
            numero = "numero",
            decimal = "decimal",
            id = "id",
            cadena = "cadena",
            caracter = "caracter",
            unario = "unario",
            poslista = "poslista",
            llamado = "llamado",
            lcasos = "lcasos",
            caso = "caso",
            seleccion = "seleccion",
            defecto = "defecto",
            para = "para",
            mientras = "mientras",
            hacer = "hacer",
            continuar = "continuar",
            terminar = "terminar",
            valor = "VALOR",
            decfun = "DECFUN",
            list = "LIST",
            lcuerpo = "LCUERPO",
            ldecfun = "LDECFUN",
            lvalor = "LVALOR",
            lcorchetes = "LCORCHETES",
            lista = "LISTA",
            lpar = "LPAR";
}
