package ide;
public class Const {
    public static final String 
            calcular = "calcular",
            let = "let",
            succ = "succ",
            decc = "decc",
            min = "min",
            max = "max",
            sum = "sum",
            product = "product",
            revers = "revers",
            impr = "impr",
            par = "par",
            asc = "asc",
            desc = "desc",
            length = "length",
            si = "si",
            sino = "sino",
            
            mas = "+",
            menos = "-",
            por = "*",
            dividido = "/",
            mod = "mod",
            sqrt = "sqrt",
            pot = "pot",
            or = "||",
            xor = "&|",
            and = "&&",
            not = "!",
            menor = "<",
            mayor = ">",
            menorigual = "<=",
            mayorigual = ">=",
            diferente = "!=",
            igualigual = "==",
            igual = "=",
            dolar = "$",
            porcentaje = "%",
            masmas = "++",
            menosmenos = "--";
    
    public static final String 
            publico = "publico",
            privado = "privado",
            protegido = "protegido",
            asignacion = "asignacion",
            declaracion = "declaracion",
            numero = "numero",
            decimal = "decimal",
            cadena = "cadena",
            caracter = "caracter",
            bool = "bool",
            id = "id",
            vacio = "vacio",
            unario = "unario",
            poslista = "poslista",
            llamado = "llamado",
            lcasos = "lcasos",
            caso = "caso",
            valor = "VALOR",
            decfun = "DECFUN",
            list = "LIST",
            lcuerpo = "LCUERPO",
            ldecfun = "LDECFUN",
            lvalor = "LVALOR",
            lcorchetes = "LCORCHETES",
            lista = "LISTA",
            lpar = "LPAR";
    
    public static final int
            tnumero = 1,
            tdecimal = 3,
            tcadena = 10,
            tcaracter = 7,
            tbool = 15,
            //tid = 11,
            tvacio = 12,
            tals = 13,
            terror = 14;
    
    public static final String 
            imprimir = "imprimir",
            importar = "importar",
            incluirhk = "incluirhk",
            hereda = "hereda",
            nuevo = "nuevo",
            seleccion = "seleccion",
            defecto = "defecto",
            para = "para",
            mientras = "mientras",
            hacer = "hacer",
            continuar = "continuar",
            graficar = "graphikar",
            terminar = "terminar",
            verdadero = "verdadero",
            falso = "falso",
            principal = "incio",
            llamar = "llamar",
            retornar = "retornar",
            limportar = "LIMPORTAR",
            lvariables = "LVARIABLES",
            lals = "LALS",
            als = "ALS",
            lid = "LID",
            lcuerpoals = "LCUERPOALS";
    
}
