/* The following code was generated by JFlex 1.6.1 */

//codigo de usuario
//paquetes e importaciones
package Analisis;
import java_cup.runtime.*;
import Reportes.*;

//opciones y declaraciones

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analisis/LexicoHaskellTerminal.jflex</tt>
 */
public class LexicoHaskellTerminal implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    48, 48, 48, 48, 48, 48, 48, 48, 48,  5,  4, 48,  5,  3, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
     5, 38, 48, 48, 39, 40, 34, 31, 45, 46, 29, 27, 47, 28, 48, 30, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 48, 48, 35, 36, 37, 48, 
    48,  7,  2,  6, 15, 11, 26, 24, 25, 18,  2,  2,  8, 16, 19, 22, 
    21, 32, 10, 14, 12,  9, 23,  2, 20,  2,  2, 43, 48, 44, 48,  2, 
    48,  7,  2,  6, 15, 11, 26, 24, 25, 18,  2,  2,  8, 16, 19, 22, 
    21, 32, 10, 14, 12,  9, 23,  2, 20,  2,  2, 41, 33, 42, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\6\2\1\0\3\2\1\0"+
    "\2\2\1\4\1\5\1\6\1\7\3\10\1\11\1\12"+
    "\1\13\1\10\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\10\1\2\1\0\6\2\1\0"+
    "\3\2\1\0\1\2\1\0\1\25\1\2\1\25\2\2"+
    "\1\26\3\0\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\2\1\0\1\2\2\35\1\36\2\2\1\0\1\2"+
    "\1\37\1\2\1\0\1\40\1\2\1\40\1\2\1\0"+
    "\1\2\1\41\2\42\1\0\1\2\1\43\1\2\3\0"+
    "\1\2\2\44\2\2\2\45\1\46\2\47\1\50\2\51"+
    "\2\52\1\2\3\0\4\2\1\0\1\53\1\54\1\2"+
    "\1\55\2\56\1\2\1\57\1\2\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df"+
    "\0\u0310\0\u0341\0\u0372\0\304\0\304\0\304\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\304\0\304\0\304"+
    "\0\304\0\304\0\304\0\304\0\304\0\304\0\304\0\u04fa"+
    "\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682"+
    "\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\304\0\u07d9"+
    "\0\142\0\u080a\0\u083b\0\304\0\u086c\0\u089d\0\u08ce\0\304"+
    "\0\304\0\304\0\304\0\304\0\304\0\u08ff\0\u0930\0\u0961"+
    "\0\304\0\142\0\142\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\142"+
    "\0\u0a56\0\u0a87\0\304\0\u0ab8\0\142\0\u0ae9\0\u0b1a\0\u0b4b"+
    "\0\142\0\304\0\142\0\u0b7c\0\u0bad\0\142\0\u0bde\0\u0c0f"+
    "\0\u0c40\0\u0c71\0\u0ca2\0\304\0\142\0\u0cd3\0\u0d04\0\304"+
    "\0\142\0\142\0\304\0\142\0\142\0\304\0\142\0\304"+
    "\0\142\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b"+
    "\0\u0e8c\0\u0ebd\0\304\0\304\0\u0eee\0\142\0\304\0\142"+
    "\0\u0f1f\0\304\0\u0f50\0\142\0\142";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\2\5\1\6\1\7\1\10"+
    "\1\3\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\3\1\22\5\3\1\23\1\24\1\25"+
    "\1\26\1\27\1\3\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\0\1\2\60\0\2\3\3\0"+
    "\7\3\1\0\3\3\1\0\11\3\5\0\1\3\24\0"+
    "\1\5\136\0\2\3\3\0\1\3\1\50\5\3\1\0"+
    "\3\3\1\0\11\3\5\0\1\3\21\0\2\3\3\0"+
    "\7\3\1\51\1\52\2\3\1\0\11\3\5\0\1\3"+
    "\21\0\2\3\3\0\5\3\1\53\1\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\21\0\2\3\3\0\5\3"+
    "\1\54\1\3\1\0\3\3\1\0\11\3\5\0\1\3"+
    "\21\0\2\3\3\0\2\3\1\55\4\3\1\0\3\3"+
    "\1\0\1\3\1\56\7\3\5\0\1\3\21\0\2\3"+
    "\3\0\7\3\1\0\3\3\1\0\7\3\1\57\1\3"+
    "\5\0\1\3\31\0\1\60\50\0\2\3\3\0\3\3"+
    "\1\61\3\3\1\0\3\3\1\0\11\3\5\0\1\3"+
    "\21\0\2\3\3\0\5\3\1\62\1\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\21\0\2\3\3\0\1\3"+
    "\1\63\5\3\1\0\3\3\1\64\1\65\10\3\5\0"+
    "\1\3\40\0\1\66\11\0\1\67\27\0\2\3\3\0"+
    "\7\3\1\0\2\3\1\70\1\0\10\3\1\71\5\0"+
    "\1\3\21\0\2\3\3\0\1\3\1\72\2\3\1\73"+
    "\2\3\1\0\3\3\1\0\11\3\5\0\1\3\53\0"+
    "\1\74\42\0\2\75\1\0\1\76\4\0\1\77\74\0"+
    "\1\100\61\0\1\101\62\0\1\102\60\0\1\103\60\0"+
    "\1\104\60\0\1\105\15\0\2\3\3\0\2\3\1\106"+
    "\4\3\1\107\1\110\2\3\1\0\11\3\5\0\1\3"+
    "\26\0\1\111\53\0\2\3\3\0\1\112\6\3\1\0"+
    "\3\3\1\0\11\3\5\0\1\3\21\0\2\3\3\0"+
    "\6\3\1\113\1\0\3\3\1\0\1\3\1\114\7\3"+
    "\5\0\1\3\21\0\2\3\3\0\7\3\1\0\3\3"+
    "\1\0\5\3\1\115\3\3\5\0\1\3\21\0\2\3"+
    "\3\0\7\3\1\116\1\117\2\3\1\0\11\3\5\0"+
    "\1\3\21\0\2\3\3\0\7\3\1\0\1\3\1\120"+
    "\1\3\1\0\11\3\5\0\1\3\21\0\2\3\3\0"+
    "\5\3\1\121\1\3\1\0\3\3\1\0\11\3\5\0"+
    "\1\3\26\0\1\122\11\0\1\123\41\0\2\3\3\0"+
    "\1\124\6\3\1\0\2\3\1\125\1\0\11\3\5\0"+
    "\1\3\21\0\2\3\3\0\1\126\6\3\1\127\1\130"+
    "\2\3\1\0\11\3\5\0\1\3\21\0\2\3\3\0"+
    "\7\3\1\0\3\3\1\0\2\3\1\131\6\3\5\0"+
    "\1\3\43\0\1\132\36\0\2\3\3\0\7\3\1\0"+
    "\3\3\1\0\1\3\1\133\7\3\5\0\1\3\45\0"+
    "\1\134\34\0\2\3\3\0\7\3\1\0\3\3\1\0"+
    "\3\3\1\135\5\3\5\0\1\3\21\0\2\3\3\0"+
    "\4\3\1\136\2\3\1\0\3\3\1\0\11\3\5\0"+
    "\1\3\21\0\2\3\3\0\7\3\1\0\3\3\1\0"+
    "\4\3\1\137\4\3\5\0\1\3\60\0\1\140\46\0"+
    "\1\141\60\0\1\142\33\0\2\3\3\0\1\143\6\3"+
    "\1\0\3\3\1\0\11\3\5\0\1\3\33\0\1\144"+
    "\46\0\2\3\3\0\5\3\1\145\1\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\21\0\2\3\3\0\7\3"+
    "\1\0\3\3\1\0\6\3\1\146\2\3\5\0\1\3"+
    "\21\0\2\3\3\0\5\3\1\147\1\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\33\0\1\150\46\0\2\3"+
    "\3\0\5\3\1\151\1\3\1\0\3\3\1\0\11\3"+
    "\5\0\1\3\21\0\2\3\3\0\7\3\1\0\3\3"+
    "\1\0\1\3\1\152\7\3\5\0\1\3\26\0\1\153"+
    "\53\0\2\3\3\0\1\154\6\3\1\0\3\3\1\0"+
    "\11\3\5\0\1\3\21\0\2\3\3\0\1\155\6\3"+
    "\1\0\3\3\1\0\11\3\5\0\1\3\26\0\1\156"+
    "\53\0\2\3\3\0\1\157\6\3\1\0\3\3\1\0"+
    "\11\3\5\0\1\3\32\0\1\160\47\0\2\3\3\0"+
    "\4\3\1\161\2\3\1\0\3\3\1\0\11\3\5\0"+
    "\1\3\21\0\2\3\3\0\7\3\1\0\1\3\1\162"+
    "\1\3\1\0\11\3\5\0\1\3\32\0\1\163\65\0"+
    "\1\164\55\0\1\165\45\0\2\3\3\0\3\3\1\166"+
    "\3\3\1\0\3\3\1\0\11\3\5\0\1\3\21\0"+
    "\2\3\3\0\6\3\1\167\1\0\3\3\1\0\11\3"+
    "\5\0\1\3\21\0\2\3\3\0\4\3\1\170\2\3"+
    "\1\0\3\3\1\0\11\3\5\0\1\3\21\0\2\3"+
    "\3\0\3\3\1\171\3\3\1\0\3\3\1\0\11\3"+
    "\5\0\1\3\34\0\1\172\103\0\1\173\60\0\1\174"+
    "\22\0\2\3\3\0\2\3\1\175\4\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\21\0\2\3\3\0\7\3"+
    "\1\0\3\3\1\0\7\3\1\176\1\3\5\0\1\3"+
    "\21\0\2\3\3\0\7\3\1\177\1\200\2\3\1\0"+
    "\11\3\5\0\1\3\21\0\2\3\3\0\1\201\6\3"+
    "\1\0\3\3\1\0\11\3\5\0\1\3\57\0\1\202"+
    "\22\0\2\3\3\0\1\3\1\203\5\3\1\0\3\3"+
    "\1\0\11\3\5\0\1\3\21\0\2\3\3\0\6\3"+
    "\1\204\1\0\3\3\1\0\11\3\5\0\1\3\21\0"+
    "\2\3\3\0\4\3\1\205\2\3\1\0\3\3\1\0"+
    "\11\3\5\0\1\3\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3969];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\1\11\6\1\1\0\3\1\1\0\3\1"+
    "\3\11\7\1\12\11\1\1\1\0\6\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\11\4\1\1\11\3\0\6\11"+
    "\1\1\1\0\1\1\1\11\4\1\1\0\3\1\1\0"+
    "\1\11\3\1\1\0\2\1\1\11\1\1\1\0\3\1"+
    "\3\0\1\1\1\11\3\1\1\11\2\1\1\11\2\1"+
    "\1\11\1\1\1\11\2\1\3\0\4\1\1\0\2\11"+
    "\2\1\1\11\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Codigo de usuario en sitaxis java por ejemplo una variable global
    public static String x;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoHaskellTerminal(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(symsHT.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(symsHT.numero, yycolumn, yyline, yytext());
            }
          case 50: break;
          case 2: 
            { return new Symbol(symsHT.iden, yycolumn, yyline, yytext());
            }
          case 51: break;
          case 3: 
            { /* ignore */
            }
          case 52: break;
          case 4: 
            { return new Symbol(symsHT.mas, yycolumn, yyline, yytext());
            }
          case 53: break;
          case 5: 
            { return new Symbol(symsHT.menos, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 6: 
            { return new Symbol(symsHT.por, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 7: 
            { return new Symbol(symsHT.dividido, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 8: 
            { ErroresHaskell.agregarError("Error Lexico", "El caracter [" + yytext() + "] no es valido", yyline, yycolumn);
            }
          case 57: break;
          case 9: 
            { return new Symbol(symsHT.menor, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 10: 
            { return new Symbol(symsHT.igual, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 11: 
            { return new Symbol(symsHT.mayor, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 12: 
            { return new Symbol(symsHT.dolar, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 13: 
            { return new Symbol(symsHT.porcentaje, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 14: 
            { return new Symbol(symsHT.allave, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 15: 
            { return new Symbol(symsHT.cllave, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 16: 
            { return new Symbol(symsHT.acorchete, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 17: 
            { return new Symbol(symsHT.ccorchete, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 18: 
            { return new Symbol(symsHT.aparentesis, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 19: 
            { return new Symbol(symsHT.cparentesis, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 20: 
            { return new Symbol(symsHT.coma, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 21: 
            { return new Symbol(symsHT._if, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 22: 
            { return new Symbol(symsHT.masmas, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 23: 
            { return new Symbol(symsHT.or, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 24: 
            { return new Symbol(symsHT.and, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 25: 
            { return new Symbol(symsHT.menorigual, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 26: 
            { return new Symbol(symsHT.igualigual, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 27: 
            { return new Symbol(symsHT.mayorigual, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 28: 
            { return new Symbol(symsHT.diferente, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 29: 
            { return new Symbol(symsHT.asc, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 30: 
            { return new Symbol(symsHT.let, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 31: 
            { return new Symbol(symsHT._end, yycolumn, yyline, yytext());
            }
          case 80: break;
          case 32: 
            { return new Symbol(symsHT.sum, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 33: 
            { return new Symbol(symsHT.max, yycolumn, yyline, yytext());
            }
          case 82: break;
          case 34: 
            { return new Symbol(symsHT.min, yycolumn, yyline, yytext());
            }
          case 83: break;
          case 35: 
            { return new Symbol(symsHT.par, yycolumn, yyline, yytext());
            }
          case 84: break;
          case 36: 
            { return new Symbol(symsHT._case, yycolumn, yyline, yytext());
            }
          case 85: break;
          case 37: 
            { return new Symbol(symsHT._else, yycolumn, yyline, yytext());
            }
          case 86: break;
          case 38: 
            { return new Symbol(symsHT._then, yycolumn, yyline, yytext());
            }
          case 87: break;
          case 39: 
            { return new Symbol(symsHT.succ, yycolumn, yyline, yytext());
            }
          case 88: break;
          case 40: 
            { return new Symbol(symsHT.decc, yycolumn, yyline, yytext());
            }
          case 89: break;
          case 41: 
            { return new Symbol(symsHT.desc, yycolumn, yyline, yytext());
            }
          case 90: break;
          case 42: 
            { return new Symbol(symsHT.impr, yycolumn, yyline, yytext());
            }
          case 91: break;
          case 43: 
            { return new Symbol(symsHT.mod, yycolumn, yyline, yytext());
            }
          case 92: break;
          case 44: 
            { return new Symbol(symsHT.pot, yycolumn, yyline, yytext());
            }
          case 93: break;
          case 45: 
            { return new Symbol(symsHT.length, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 46: 
            { return new Symbol(symsHT.revers, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 47: 
            { return new Symbol(symsHT.sqrt, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 48: 
            { return new Symbol(symsHT.product, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 49: 
            { return new Symbol(symsHT.calcular, yycolumn, yyline, yytext());
            }
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
