
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class SimbolosHaskellTerminal {
  /* terminals */
  public static final int decc = 5;
  public static final int ccorchete = 43;
  public static final int allave = 40;
  public static final int igualigual = 36;
  public static final int cllave = 41;
  public static final int mod = 26;
  public static final int par = 12;
  public static final int acorchete = 42;
  public static final int coma = 46;
  public static final int asc = 13;
  public static final int igual = 37;
  public static final int calcular = 2;
  public static final int let = 3;
  public static final int succ = 4;
  public static final int dividido = 25;
  public static final int _end = 19;
  public static final int sum = 8;
  public static final int _else = 18;
  public static final int length = 15;
  public static final int iden = 48;
  public static final int numero = 47;
  public static final int masmas = 21;
  public static final int max = 7;
  public static final int menos = 23;
  public static final int _then = 17;
  public static final int menor = 33;
  public static final int porcentaje = 39;
  public static final int EOF = 0;
  public static final int mas = 22;
  public static final int revers = 10;
  public static final int error = 1;
  public static final int mayor = 34;
  public static final int or = 29;
  public static final int pot = 28;
  public static final int menorigual = 31;
  public static final int por = 24;
  public static final int _if = 16;
  public static final int cparentesis = 45;
  public static final int sqrt = 27;
  public static final int product = 9;
  public static final int impr = 11;
  public static final int mayorigual = 32;
  public static final int desc = 14;
  public static final int aparentesis = 44;
  public static final int diferente = 35;
  public static final int and = 30;
  public static final int _case = 20;
  public static final int dolar = 38;
  public static final int min = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "calcular",
  "let",
  "succ",
  "decc",
  "min",
  "max",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "asc",
  "desc",
  "length",
  "_if",
  "_then",
  "_else",
  "_end",
  "_case",
  "masmas",
  "mas",
  "menos",
  "por",
  "dividido",
  "mod",
  "sqrt",
  "pot",
  "or",
  "and",
  "menorigual",
  "mayorigual",
  "menor",
  "mayor",
  "diferente",
  "igualigual",
  "igual",
  "dolar",
  "porcentaje",
  "allave",
  "cllave",
  "acorchete",
  "ccorchete",
  "aparentesis",
  "cparentesis",
  "coma",
  "numero",
  "iden"
  };
}

