/* The following code was generated by JFlex 1.6.1 */

//codigo de usuario
//paquetes e importaciones
package Analisis.graphik;
import java_cup.runtime.*;
import Reportes.*;

//opciones y declaraciones

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analisis/graphik/LexicoGraphik.jflex</tt>
 */
public class LexicoGraphik implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    58, 58, 58, 58, 58, 58, 58, 58, 58, 12,  5,  7,  8,  6, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    12, 45, 10, 13, 58, 58, 44,  4, 56, 57, 41, 39, 51, 40,  2, 14, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 50, 58, 46, 47, 48, 49, 
    58, 16, 29, 24, 23, 20, 38, 31, 36, 26,  3, 33, 28, 27, 18, 21, 
    30,  3, 17, 35, 22, 19, 15,  3,  3,  3,  3, 54, 11, 55, 42, 37, 
    58, 16, 29, 24, 23, 20, 38, 31, 36, 26,  3, 33, 28, 27, 18, 21, 
    30,  3, 17, 35, 22, 19, 15,  3,  3,  3,  3, 52, 43, 53, 58, 58, 
    58, 58, 58, 58, 58,  7, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\2\5\3\4\1\6"+
    "\10\3\1\0\6\3\1\0\3\3\1\7\1\10\1\11"+
    "\1\12\2\4\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\4\0"+
    "\1\30\2\0\1\31\1\0\14\3\2\0\2\3\1\0"+
    "\7\3\1\0\1\32\1\3\1\32\3\3\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\30\1\31\2\0\1\47\2\3\2\50"+
    "\12\3\1\0\3\3\3\0\3\3\1\0\5\3\1\0"+
    "\3\3\2\0\5\3\4\0\1\51\1\0\7\3\1\0"+
    "\5\3\2\52\2\3\4\0\4\3\1\0\2\3\1\53"+
    "\1\54\2\3\1\0\3\3\1\0\1\55\1\3\1\55"+
    "\2\3\1\0\1\3\1\0\1\51\2\56\2\3\1\57"+
    "\1\3\1\0\1\3\2\60\1\0\2\3\1\61\2\3"+
    "\1\0\2\3\4\0\4\3\1\0\4\3\1\0\1\3"+
    "\1\0\2\3\1\0\1\3\1\62\1\3\2\63\2\3"+
    "\1\64\1\0\1\3\1\0\5\3\1\65\1\0\2\3"+
    "\1\0\1\66\2\0\1\3\1\66\2\3\1\0\1\3"+
    "\1\67\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\70\2\3\1\0\1\3"+
    "\2\71\1\72\3\3\1\0\1\3\1\73\3\0\3\3"+
    "\1\0\2\3\1\0\1\3\1\0\1\3\2\74\2\75"+
    "\1\0\1\3\1\0\2\3\1\76\2\77\2\3\1\100"+
    "\1\0\1\3\1\0\1\101\1\102\1\3\1\101\1\102"+
    "\2\103\2\104\1\0\1\3\2\105\1\0\1\3\1\0"+
    "\1\3\1\106\1\107\1\110\2\111\1\0\1\3\2\112"+
    "\1\0\1\3\2\113\2\114\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\2\115";

  private static int [] zzUnpackAction() {
    int [] result = new int[373];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u0162\0\u01d8\0\u0213\0\u0162\0\u024e\0\u0289\0\u02c4\0\u02ff"+
    "\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674\0\u06af"+
    "\0\u06ea\0\u0162\0\u0162\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811"+
    "\0\u084c\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162"+
    "\0\u0162\0\u0162\0\u0887\0\u08c2\0\u08fd\0\u01d8\0\u0162\0\u0938"+
    "\0\u0973\0\u0162\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5"+
    "\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad"+
    "\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85"+
    "\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7\0\u1022\0\u105d"+
    "\0\u1098\0\u10d3\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162"+
    "\0\u0162\0\u0162\0\u0162\0\u0887\0\u0162\0\u0162\0\u01d8\0\u110e"+
    "\0\u1149\0\u1184\0\354\0\u11bf\0\u11fa\0\u0162\0\354\0\u1235"+
    "\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d"+
    "\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5"+
    "\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd"+
    "\0\u17f8\0\u1833\0\u186e\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995"+
    "\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u110e\0\u1abc\0\u1af7\0\u1b32"+
    "\0\u0973\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\u1c59\0\u1c94\0\u1ccf"+
    "\0\u1d0a\0\u1d45\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\u1e6c\0\u0162"+
    "\0\354\0\u1ea7\0\u1ee2\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u2009"+
    "\0\u2044\0\u207f\0\u20ba\0\u20f5\0\u2130\0\u216b\0\354\0\354"+
    "\0\u21a6\0\u21e1\0\u221c\0\u2257\0\u2292\0\u22cd\0\u2308\0\u0162"+
    "\0\u2343\0\354\0\u237e\0\u23b9\0\u23f4\0\u242f\0\u246a\0\u0162"+
    "\0\u0162\0\354\0\u24a5\0\u24e0\0\354\0\u251b\0\u2556\0\u2591"+
    "\0\u0162\0\354\0\u25cc\0\u2607\0\u2642\0\u267d\0\u26b8\0\u26f3"+
    "\0\u272e\0\u2769\0\u27a4\0\u27df\0\u281a\0\u2855\0\u2890\0\u28cb"+
    "\0\u2906\0\u2941\0\u297c\0\u29b7\0\u29f2\0\u2a2d\0\u2a68\0\u2aa3"+
    "\0\u2ade\0\u2b19\0\u2b54\0\u2b8f\0\u2bca\0\u2c05\0\u2c40\0\354"+
    "\0\u2c7b\0\u0162\0\354\0\u2cb6\0\u2cf1\0\354\0\u2d2c\0\u2d67"+
    "\0\u2da2\0\u2ddd\0\u2e18\0\u2e53\0\u2e8e\0\u2ec9\0\354\0\u2f04"+
    "\0\u2f3f\0\u2f7a\0\u2fb5\0\u0162\0\u2ff0\0\u302b\0\u3066\0\354"+
    "\0\u30a1\0\u30dc\0\u3117\0\u3152\0\u318d\0\u31c8\0\u3203\0\u323e"+
    "\0\u3279\0\u32b4\0\u32ef\0\u332a\0\u3365\0\u33a0\0\u33db\0\u3416"+
    "\0\354\0\u3451\0\u348c\0\u34c7\0\u3502\0\u0162\0\354\0\354"+
    "\0\u353d\0\u3578\0\u35b3\0\u35ee\0\u3629\0\354\0\u3664\0\u369f"+
    "\0\u36da\0\u3715\0\u3750\0\u378b\0\u37c6\0\u3801\0\u383c\0\u3877"+
    "\0\u38b2\0\u38ed\0\u3928\0\u0162\0\354\0\u0162\0\354\0\u3963"+
    "\0\u399e\0\u39d9\0\u3a14\0\u3a4f\0\354\0\u0162\0\354\0\u3a8a"+
    "\0\u3ac5\0\354\0\u3b00\0\u3b3b\0\u3b76\0\u0162\0\u0162\0\u3bb1"+
    "\0\354\0\354\0\u0162\0\354\0\u0162\0\354\0\u3bec\0\u3c27"+
    "\0\u0162\0\354\0\u3c62\0\u3c9d\0\u3cd8\0\u3d13\0\354\0\354"+
    "\0\354\0\u0162\0\354\0\u3d4e\0\u3d89\0\u0162\0\354\0\u3dc4"+
    "\0\u3dff\0\u0162\0\354\0\u0162\0\354\0\u3e3a\0\u3e75\0\u3eb0"+
    "\0\u3eeb\0\u3f26\0\u3f61\0\u3f9c\0\u3fd7\0\u4012\0\u404d\0\u4088"+
    "\0\u40c3\0\u40fe\0\u4139\0\u0162\0\354";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[373];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\7\1\0\1\12\1\11\1\7\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\5\1\21\1\5\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\0\1\5\1\34\1\35\1\36\1\5\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\11\1\0\10\11\1\0\17\11\1\0"+
    "\6\11\1\0\1\11\1\0\30\11\1\0\1\3\1\63"+
    "\127\0\1\64\34\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\24\0\5\65"+
    "\5\0\61\65\100\0\1\7\65\0\12\66\1\67\1\70"+
    "\57\66\5\71\1\72\10\71\1\73\54\71\1\0\1\5"+
    "\1\0\1\5\13\0\1\5\1\74\3\5\1\75\4\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\12\5\1\0\2\5\1\76\3\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\5\5\1\77\4\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\4\5"+
    "\1\100\5\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\3\5\1\101\6\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\5\5\1\102\4\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\1\5\1\103\3\5\1\104\1\105\3\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\1\5\1\106\4\5\1\107\3\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\46\0\1\110\10\0"+
    "\1\111\40\0\1\5\1\0\1\5\13\0\3\5\1\112"+
    "\6\5\1\0\1\5\1\113\4\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\12\5\1\114"+
    "\1\115\5\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\12\5\1\0\2\5\1\116\3\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\6\5\1\117\3\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\1\5"+
    "\1\120\1\121\1\5\1\122\5\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\2\5\1\123\7\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\50\0\1\124\4\0\2\125\41\0\1\5\1\0"+
    "\1\5\13\0\5\5\1\126\4\5\1\125\1\127\5\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\1\5\1\130\3\5\1\131\4\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\1\5\1\132\10\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\73\0\1\133\73\0\1\134\75\0\1\135"+
    "\72\0\1\136\1\137\75\0\1\140\72\0\1\141\72\0"+
    "\1\142\72\0\1\143\14\0\1\144\131\0\2\145\35\0"+
    "\1\146\66\0\12\66\1\147\1\70\57\66\5\71\1\72"+
    "\65\71\5\73\1\150\5\73\1\151\1\73\1\71\1\152"+
    "\54\73\1\0\1\5\1\0\1\5\13\0\2\5\1\153"+
    "\6\5\1\154\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\2\5\1\155\7\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\12\5\1\0\6\5\1\0\1\5"+
    "\1\156\1\157\3\5\25\0\1\5\1\0\1\5\13\0"+
    "\7\5\1\160\2\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\5\5\1\161"+
    "\4\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\7\5\1\162\2\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\2\5\1\163\7\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\7\5\1\164\2\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\11\5\1\165"+
    "\1\0\6\5\1\0\1\5\1\0\3\5\1\166\25\0"+
    "\1\5\1\0\1\5\13\0\3\5\1\167\6\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\2\5\1\170\5\5\1\171\1\5\1\0"+
    "\6\5\1\0\1\5\1\172\1\173\3\5\25\0\1\5"+
    "\1\0\1\5\13\0\3\5\1\174\6\5\1\0\2\5"+
    "\1\175\3\5\1\0\1\5\1\0\4\5\54\0\1\176"+
    "\2\177\76\0\1\200\35\0\1\5\1\0\1\5\13\0"+
    "\11\5\1\201\1\177\1\202\5\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\4\5\1\203\1\5\1\0\1\5\1\0\4\5\50\0"+
    "\1\204\47\0\1\5\1\0\1\5\13\0\5\5\1\205"+
    "\4\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\1\5\1\206\10\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\6\5\1\207\3\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\2\5\1\210\7\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\6\5\1\211"+
    "\3\5\1\212\1\213\5\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\12\5\1\0\3\5"+
    "\1\214\2\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\1\5\1\215\10\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\60\0\1\216\60\0\1\217"+
    "\51\0\1\5\1\0\1\5\13\0\12\5\1\0\2\5"+
    "\1\220\3\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\3\5\1\221\6\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\11\5\1\222\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\2\5\1\223"+
    "\7\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\0\2\5\1\224"+
    "\3\5\1\0\1\5\1\0\4\5\24\0\13\225\1\226"+
    "\1\225\1\0\1\227\54\225\5\73\1\150\5\73\1\151"+
    "\2\73\1\230\54\73\5\71\1\72\7\71\1\231\55\71"+
    "\1\0\1\5\1\0\1\5\13\0\12\5\1\232\1\233"+
    "\5\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\10\5\1\234\1\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\6\5\1\235\3\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\1\236\11\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\5\5\1\237\4\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\1\5\1\240\4\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\6\5"+
    "\1\241\3\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\12\5\1\242\1\243"+
    "\5\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\5\5\1\244\4\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\10\5\1\245\1\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\1\5\1\246"+
    "\10\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\5\5\1\247\4\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\51\0\1\250\46\0"+
    "\1\5\1\0\1\5\13\0\6\5\1\251\3\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\7\5\1\252\2\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\4\5\1\253\5\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\60\0\1\254\66\0\1\255\63\0\1\256\3\0"+
    "\1\257\46\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\2\5\1\260\3\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\11\5\1\261\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\262\3\5\1\263\3\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\46\0\1\264\51\0\1\5"+
    "\1\0\1\5\13\0\3\5\1\265\6\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\1\5\1\266\4\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\0\2\5\1\267\3\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\1\5\1\270\10\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\7\5\1\271\1\5\1\272\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\43\0\1\273\54\0"+
    "\1\5\1\0\1\5\13\0\1\274\11\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\2\5\1\275\3\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\0\4\5\1\276\1\5\1\0\1\5\1\0\4\5"+
    "\50\0\1\277\73\0\1\300\46\0\1\5\1\0\1\5"+
    "\13\0\5\5\1\301\4\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\6\5"+
    "\1\302\3\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\5\5\1\303\4\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\5\5\1\304\4\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\6\5\1\0\1\5\1\305\1\306"+
    "\3\5\24\0\13\225\1\226\2\225\1\307\54\225\15\0"+
    "\1\310\55\0\5\73\1\150\5\73\1\151\1\73\1\231"+
    "\1\152\54\73\25\0\1\311\46\0\1\5\1\0\1\5"+
    "\13\0\6\5\1\312\3\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\1\5"+
    "\1\313\10\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\2\5\1\314\7\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\6\5\1\315\3\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\316\7\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\317\1\320\5\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\0\6\5\1\0"+
    "\1\5\1\321\1\322\3\5\57\0\1\323\40\0\1\5"+
    "\1\0\1\5\13\0\12\5\1\0\1\5\1\324\4\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\11\5\1\325\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\5\5\1\326"+
    "\4\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\11\5\1\327\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\3\5\1\330\6\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\331\1\332\5\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\0\1\5\1\333"+
    "\4\5\1\0\1\5\1\0\4\5\47\0\1\334\100\0"+
    "\2\335\71\0\2\336\61\0\1\337\52\0\1\5\1\0"+
    "\1\5\13\0\4\5\1\340\5\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\12\5\1\335\1\341\5\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\12\5\1\336\1\342"+
    "\5\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\2\5\1\343\7\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\52\0\1\344\45\0\1\5\1\0"+
    "\1\5\13\0\7\5\1\345\2\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\1\5\1\346\10\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\5\5\1\347"+
    "\4\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\5\5\1\350\4\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\44\0\1\351\53\0"+
    "\1\5\1\0\1\5\13\0\1\5\1\352\10\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\12\5\1\353\1\354\5\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\0\6\5\1\0\1\5\1\0\1\5\1\355\2\5"+
    "\54\0\1\356\43\0\1\5\1\0\1\5\13\0\11\5"+
    "\1\357\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\2\5\1\360\7\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\10\5\1\361\1\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\51\0\1\362\46\0\1\5\1\0"+
    "\1\5\13\0\6\5\1\363\3\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\24\0\13\225\1\226\1\225\1\310"+
    "\1\227\54\225\1\0\1\5\1\0\1\5\13\0\10\5"+
    "\1\364\1\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\3\5\1\365\6\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\6\5\1\366\3\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\46\0\1\367\51\0\1\5"+
    "\1\0\1\5\13\0\3\5\1\370\6\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\44\0\1\371\53\0\1\5"+
    "\1\0\1\5\13\0\1\5\1\372\10\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\7\5\1\373\2\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\7\5"+
    "\1\374\1\5\1\375\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\7\5\1\376"+
    "\2\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\1\5\1\377\10\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\46\0\1\u0100\51\0"+
    "\1\5\1\0\1\5\13\0\3\5\1\u0101\6\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\3\5\1\u0102\6\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\55\0\2\u0103\65\0\1\u0104\100\0"+
    "\1\u0105\65\0\1\u0106\45\0\1\5\1\0\1\5\13\0"+
    "\12\5\1\u0103\1\u0107\5\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\6\5\1\u0108\3\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\12\5\1\0\1\5\1\u0109\4\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\7\5\1\u010a\2\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\45\0\1\u010b\52\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\u010c\7\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\2\5"+
    "\1\u010d\7\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\12\5\1\0\5\5"+
    "\1\u010e\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\12\5\1\0\6\5\1\0\1\5\1\u010f"+
    "\1\u0110\3\5\53\0\1\u0111\44\0\1\5\1\0\1\5"+
    "\13\0\10\5\1\u0112\1\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\54\0\1\u0113\43\0\1\5\1\0\1\5"+
    "\13\0\11\5\1\u0114\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\12\5\1\u0115"+
    "\1\u0116\5\5\1\0\1\5\1\0\4\5\54\0\1\u0117"+
    "\43\0\1\5\1\0\1\5\13\0\11\5\1\u0118\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\1\5\1\u0119\10\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\5\5\1\u011a\4\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\1\5\1\u011b"+
    "\10\5\1\0\6\5\1\0\1\5\1\0\4\5\44\0"+
    "\1\u011c\53\0\1\5\1\0\1\5\13\0\1\5\1\u011d"+
    "\10\5\1\0\6\5\1\0\1\5\1\0\4\5\60\0"+
    "\1\u011e\37\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\2\5\1\u011f\3\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\6\5\1\u0120\3\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\6\5\1\u0121\3\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\1\5\1\u0122\10\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\5\5\1\u0123"+
    "\4\5\1\0\6\5\1\0\1\5\1\0\4\5\47\0"+
    "\1\u0124\50\0\1\5\1\0\1\5\13\0\4\5\1\u0125"+
    "\5\5\1\0\6\5\1\0\1\5\1\0\4\5\25\0"+
    "\1\5\1\0\1\5\13\0\1\5\1\u0126\10\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\45\0\1\u0127\102\0"+
    "\2\u0128\60\0\1\u0129\53\0\1\5\1\0\1\5\13\0"+
    "\2\5\1\u012a\7\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\12\5\1\u0128"+
    "\1\u012b\5\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\1\5\1\u012c\10\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\44\0\1\u012d\53\0\1\5"+
    "\1\0\1\5\13\0\1\5\1\u012e\10\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\6\5\1\0\1\5\1\0\1\5"+
    "\1\u012f\2\5\25\0\1\5\1\0\1\5\13\0\12\5"+
    "\1\u0130\1\u0131\5\5\1\0\1\5\1\0\4\5\44\0"+
    "\1\u0132\53\0\1\5\1\0\1\5\13\0\1\5\1\u0133"+
    "\10\5\1\0\6\5\1\0\1\5\1\0\4\5\51\0"+
    "\1\u0134\46\0\1\5\1\0\1\5\13\0\6\5\1\u0135"+
    "\3\5\1\0\6\5\1\0\1\5\1\0\4\5\51\0"+
    "\1\u0136\46\0\1\5\1\0\1\5\13\0\6\5\1\u0137"+
    "\3\5\1\0\6\5\1\0\1\5\1\0\4\5\64\0"+
    "\2\u0138\32\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\6\5\1\u0138\1\u0139\1\0\4\5\55\0\2\u013a\41\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\u013a\1\u013b\5\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\u013c\7\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\25\0\1\5\1\0\1\5\13\0\2\5"+
    "\1\u013d\7\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\45\0\1\u013e\52\0\1\5\1\0\1\5\13\0\2\5"+
    "\1\u013f\7\5\1\0\6\5\1\0\1\5\1\0\4\5"+
    "\25\0\1\5\1\0\1\5\13\0\10\5\1\u0140\1\5"+
    "\1\0\6\5\1\0\1\5\1\0\4\5\25\0\1\5"+
    "\1\0\1\5\13\0\10\5\1\u0141\1\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\u0142\7\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\44\0\1\u0143\53\0\1\5\1\0\1\5"+
    "\13\0\1\5\1\u0144\10\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\71\0\1\u0145\46\0\1\u0146\72\0\1\u0147"+
    "\52\0\1\5\1\0\1\5\13\0\12\5\1\0\6\5"+
    "\1\0\1\5\1\0\2\5\1\u0148\1\5\25\0\1\5"+
    "\1\0\1\5\13\0\2\5\1\u0149\7\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\25\0\1\5\1\0\1\5"+
    "\13\0\2\5\1\u014a\7\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\66\0\2\u014b\30\0\1\5\1\0\1\5"+
    "\13\0\12\5\1\0\6\5\1\0\1\5\1\u014b\1\u014c"+
    "\3\5\25\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\6\5\1\u014d\1\u014e\1\0\4\5\53\0\1\u014f\44\0"+
    "\1\5\1\0\1\5\13\0\10\5\1\u0150\1\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\45\0\1\u0151\52\0"+
    "\1\5\1\0\1\5\13\0\2\5\1\u0152\7\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\44\0\1\u0153\53\0"+
    "\1\5\1\0\1\5\13\0\1\5\1\u0154\10\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\51\0\1\u0155\46\0"+
    "\1\5\1\0\1\5\13\0\6\5\1\u0156\3\5\1\0"+
    "\6\5\1\0\1\5\1\0\4\5\25\0\1\5\1\0"+
    "\1\5\13\0\6\5\1\u0157\3\5\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\25\0\1\5\1\0\1\5\13\0"+
    "\6\5\1\u0158\3\5\1\0\6\5\1\0\1\5\1\0"+
    "\4\5\25\0\1\5\1\0\1\5\13\0\1\5\1\u0159"+
    "\10\5\1\0\6\5\1\0\1\5\1\0\4\5\45\0"+
    "\1\u015a\52\0\1\5\1\0\1\5\13\0\2\5\1\u015b"+
    "\7\5\1\0\6\5\1\0\1\5\1\0\4\5\70\0"+
    "\1\u015c\27\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\6\5\1\0\1\5\1\0\1\5\1\u015d\2\5\51\0"+
    "\1\u015e\46\0\1\5\1\0\1\5\13\0\6\5\1\u015f"+
    "\3\5\1\0\6\5\1\0\1\5\1\0\4\5\45\0"+
    "\1\u0160\52\0\1\5\1\0\1\5\13\0\2\5\1\u0161"+
    "\7\5\1\0\6\5\1\0\1\5\1\0\4\5\46\0"+
    "\1\u0162\51\0\1\5\1\0\1\5\13\0\3\5\1\u0163"+
    "\6\5\1\0\6\5\1\0\1\5\1\0\4\5\64\0"+
    "\2\u0164\32\0\1\5\1\0\1\5\13\0\12\5\1\0"+
    "\6\5\1\u0164\1\u0165\1\0\4\5\71\0\1\u0166\26\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\0\6\5\1\0"+
    "\1\5\1\0\2\5\1\u0167\1\5\72\0\1\u0168\25\0"+
    "\1\5\1\0\1\5\13\0\12\5\1\0\6\5\1\0"+
    "\1\5\1\0\3\5\1\u0169\47\0\1\u016a\50\0\1\5"+
    "\1\0\1\5\13\0\4\5\1\u016b\5\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\46\0\1\u016c\51\0\1\5"+
    "\1\0\1\5\13\0\3\5\1\u016d\6\5\1\0\6\5"+
    "\1\0\1\5\1\0\4\5\54\0\1\u016e\43\0\1\5"+
    "\1\0\1\5\13\0\11\5\1\u016f\1\0\6\5\1\0"+
    "\1\5\1\0\4\5\55\0\2\u0170\41\0\1\5\1\0"+
    "\1\5\13\0\12\5\1\u0170\1\u0171\5\5\1\0\1\5"+
    "\1\0\4\5\51\0\1\u0172\46\0\1\5\1\0\1\5"+
    "\13\0\6\5\1\u0173\3\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\46\0\1\u0174\51\0\1\5\1\0\1\5"+
    "\13\0\3\5\1\u0175\6\5\1\0\6\5\1\0\1\5"+
    "\1\0\4\5\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16756];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\4\1\1\11\1\1\1\11\2\1\1\11\10\1"+
    "\1\0\6\1\1\0\5\1\2\11\6\1\11\11\4\0"+
    "\1\11\2\0\1\11\1\0\14\1\2\0\2\1\1\0"+
    "\7\1\1\0\6\1\11\11\1\1\2\11\2\1\2\0"+
    "\3\1\1\11\13\1\1\0\3\1\3\0\3\1\1\0"+
    "\5\1\1\0\3\1\2\0\5\1\4\0\1\1\1\0"+
    "\7\1\1\0\5\1\1\11\3\1\4\0\4\1\1\0"+
    "\6\1\1\0\3\1\1\0\1\11\4\1\1\0\1\1"+
    "\1\0\2\11\5\1\1\0\1\1\1\11\1\1\1\0"+
    "\5\1\1\0\2\1\4\0\4\1\1\0\4\1\1\0"+
    "\1\1\1\0\2\1\1\0\3\1\1\11\4\1\1\0"+
    "\1\1\1\0\6\1\1\0\2\1\1\0\1\11\2\0"+
    "\4\1\1\0\3\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\4\1\1\0\1\1\1\11"+
    "\5\1\1\0\2\1\3\0\3\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1\1\11\1\1\1\0"+
    "\1\1\1\0\3\1\1\11\4\1\1\0\1\1\1\0"+
    "\2\11\3\1\1\11\1\1\1\11\1\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\0\4\1\1\11\1\1"+
    "\1\0\1\1\1\11\1\1\1\0\1\1\1\11\1\1"+
    "\1\11\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[373];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Codigo de usuario en sitaxis java por ejemplo una variable global
    StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoGraphik(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(symsG.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(symsG.numero, yycolumn, yyline, Integer.valueOf(yytext()) + "");
            }
          case 78: break;
          case 2: 
            { return new Symbol(symsG.punto, yycolumn, yyline, yytext().toLowerCase());
            }
          case 79: break;
          case 3: 
            { return new Symbol(symsG.iden, yycolumn, yyline, yytext().toLowerCase());
            }
          case 80: break;
          case 4: 
            { ErroresGraphik.agregarError("Error Lexico", "El caracter [" + yytext() + "] no es valido", yyline, yycolumn);
            }
          case 81: break;
          case 5: 
            { /* ignore */
            }
          case 82: break;
          case 6: 
            { return new Symbol(symsG.dividido, yycolumn, yyline, yytext().toLowerCase());
            }
          case 83: break;
          case 7: 
            { return new Symbol(symsG.mas, yycolumn, yyline, yytext().toLowerCase());
            }
          case 84: break;
          case 8: 
            { return new Symbol(symsG.menos, yycolumn, yyline, yytext().toLowerCase());
            }
          case 85: break;
          case 9: 
            { return new Symbol(symsG.por, yycolumn, yyline, yytext().toLowerCase());
            }
          case 86: break;
          case 10: 
            { return new Symbol(symsG.pot, yycolumn, yyline, yytext().toLowerCase());
            }
          case 87: break;
          case 11: 
            { return new Symbol(symsG.not, yycolumn, yyline, yytext().toLowerCase());
            }
          case 88: break;
          case 12: 
            { return new Symbol(symsG.menor, yycolumn, yyline, yytext().toLowerCase());
            }
          case 89: break;
          case 13: 
            { return new Symbol(symsG.igual, yycolumn, yyline, yytext().toLowerCase());
            }
          case 90: break;
          case 14: 
            { return new Symbol(symsG.mayor, yycolumn, yyline, yytext().toLowerCase());
            }
          case 91: break;
          case 15: 
            { return new Symbol(symsG.interroga, yycolumn, yyline, yytext().toLowerCase());
            }
          case 92: break;
          case 16: 
            { return new Symbol(symsG.dospuntos, yycolumn, yyline, yytext().toLowerCase());
            }
          case 93: break;
          case 17: 
            { return new Symbol(symsG.coma, yycolumn, yyline, yytext().toLowerCase());
            }
          case 94: break;
          case 18: 
            { return new Symbol(symsG.allave, yycolumn, yyline, yytext().toLowerCase());
            }
          case 95: break;
          case 19: 
            { return new Symbol(symsG.cllave, yycolumn, yyline, yytext().toLowerCase());
            }
          case 96: break;
          case 20: 
            { return new Symbol(symsG.acorchete, yycolumn, yyline, yytext().toLowerCase());
            }
          case 97: break;
          case 21: 
            { return new Symbol(symsG.ccorchete, yycolumn, yyline, yytext().toLowerCase());
            }
          case 98: break;
          case 22: 
            { return new Symbol(symsG.aparentesis, yycolumn, yyline, yytext().toLowerCase());
            }
          case 99: break;
          case 23: 
            { return new Symbol(symsG.cparentesis, yycolumn, yyline, yytext().toLowerCase());
            }
          case 100: break;
          case 24: 
            { return new Symbol(symsG.cad, yycolumn, yyline, yytext().replace("\"", ""));
            }
          case 101: break;
          case 25: 
            { System.out.println("Comentario liena");
            }
          case 102: break;
          case 26: 
            { return new Symbol(symsG.si, yycolumn, yyline, yytext().toLowerCase());
            }
          case 103: break;
          case 27: 
            { return new Symbol(symsG.masmas, yycolumn, yyline, yytext().toLowerCase());
            }
          case 104: break;
          case 28: 
            { return new Symbol(symsG.menosmenos, yycolumn, yyline, yytext().toLowerCase());
            }
          case 105: break;
          case 29: 
            { return new Symbol(symsG.or, yycolumn, yyline, yytext().toLowerCase());
            }
          case 106: break;
          case 30: 
            { return new Symbol(symsG.xor, yycolumn, yyline, yytext().toLowerCase());
            }
          case 107: break;
          case 31: 
            { return new Symbol(symsG.and, yycolumn, yyline, yytext().toLowerCase());
            }
          case 108: break;
          case 32: 
            { return new Symbol(symsG.diferente, yycolumn, yyline, yytext().toLowerCase());
            }
          case 109: break;
          case 33: 
            { return new Symbol(symsG.menorigual, yycolumn, yyline, yytext().toLowerCase());
            }
          case 110: break;
          case 34: 
            { return new Symbol(symsG.igualigual, yycolumn, yyline, yytext().toLowerCase());
            }
          case 111: break;
          case 35: 
            { return new Symbol(symsG.mayorigual, yycolumn, yyline, yytext().toLowerCase());
            }
          case 112: break;
          case 36: 
            { return new Symbol(symsG.dec, yycolumn, yyline, Double.valueOf(yytext()) + "");
            }
          case 113: break;
          case 37: 
            { return new Symbol(symsG.extgk, yycolumn, yyline, yytext().toLowerCase());
            }
          case 114: break;
          case 38: 
            { return new Symbol(symsG.car, yycolumn, yyline, yytext().replace("'", ""));
            }
          case 115: break;
          case 39: 
            { return new Symbol(symsG.var, yycolumn, yyline, yytext().toLowerCase());
            }
          case 116: break;
          case 40: 
            { return new Symbol(symsG.als, yycolumn, yyline, yytext().toLowerCase());
            }
          case 117: break;
          case 41: 
            { System.out.println("Comentario bloque");
            }
          case 118: break;
          case 42: 
            { return new Symbol(symsG.caso, yycolumn, yyline, yytext().toLowerCase());
            }
          case 119: break;
          case 43: 
            { return new Symbol(symsG.bool, yycolumn, yyline, yytext().toLowerCase());
            }
          case 120: break;
          case 44: 
            { return new Symbol(symsG.para, yycolumn, yyline, yytext().toLowerCase());
            }
          case 121: break;
          case 45: 
            { return new Symbol(symsG.sino, yycolumn, yyline, yytext().toLowerCase());
            }
          case 122: break;
          case 46: 
            { return new Symbol(symsG.vacio, yycolumn, yyline, yytext().toLowerCase());
            }
          case 123: break;
          case 47: 
            { return new Symbol(symsG.nuevo, yycolumn, yyline, yytext().toLowerCase());
            }
          case 124: break;
          case 48: 
            { return new Symbol(symsG.datos, yycolumn, yyline, yytext().toLowerCase());
            }
          case 125: break;
          case 49: 
            { return new Symbol(symsG.donde, yycolumn, yyline, yytext().toLowerCase());
            }
          case 126: break;
          case 50: 
            { return new Symbol(symsG.hacer, yycolumn, yyline, yytext().toLowerCase());
            }
          case 127: break;
          case 51: 
            { return new Symbol(symsG.falso, yycolumn, yyline, yytext().toLowerCase());
            }
          case 128: break;
          case 52: 
            { return new Symbol(symsG.entero, yycolumn, yyline, yytext().toLowerCase());
            }
          case 129: break;
          case 53: 
            { return new Symbol(symsG.cadena, yycolumn, yyline, yytext().toLowerCase());
            }
          case 130: break;
          case 54: 
            { return new Symbol(symsG.inicio, yycolumn, yyline, yytext().toLowerCase());
            }
          case 131: break;
          case 55: 
            { return new Symbol(symsG.llamar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 132: break;
          case 56: 
            { return new Symbol(symsG.hereda, yycolumn, yyline, yytext().toLowerCase());
            }
          case 133: break;
          case 57: 
            { return new Symbol(symsG.decimal, yycolumn, yyline, yytext().toLowerCase());
            }
          case 134: break;
          case 58: 
            { return new Symbol(symsG.defecto, yycolumn, yyline, yytext().toLowerCase());
            }
          case 135: break;
          case 59: 
            { return new Symbol(symsG.columna, yycolumn, yyline, yytext().toLowerCase());
            }
          case 136: break;
          case 60: 
            { return new Symbol(symsG.privado, yycolumn, yyline, yytext().toLowerCase());
            }
          case 137: break;
          case 61: 
            { return new Symbol(symsG.publico, yycolumn, yyline, yytext().toLowerCase());
            }
          case 138: break;
          case 62: 
            { return new Symbol(symsG.retornar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 139: break;
          case 63: 
            { return new Symbol(symsG.terminar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 140: break;
          case 64: 
            { return new Symbol(symsG.caracter, yycolumn, yyline, yytext().toLowerCase());
            }
          case 141: break;
          case 65: 
            { return new Symbol(symsG.imprimir, yycolumn, yyline, yytext().toLowerCase());
            }
          case 142: break;
          case 66: 
            { return new Symbol(symsG.importar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 143: break;
          case 67: 
            { return new Symbol(symsG.mientras, yycolumn, yyline, yytext().toLowerCase());
            }
          case 144: break;
          case 68: 
            { return new Symbol(symsG.llamarhk, yycolumn, yyline, yytext().toLowerCase());
            }
          case 145: break;
          case 69: 
            { return new Symbol(symsG.procesar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 146: break;
          case 70: 
            { return new Symbol(symsG.verdadero, yycolumn, yyline, yytext().toLowerCase());
            }
          case 147: break;
          case 71: 
            { return new Symbol(symsG.dondetodo, yycolumn, yyline, yytext().toLowerCase());
            }
          case 148: break;
          case 72: 
            { return new Symbol(symsG.dondecada, yycolumn, yyline, yytext().toLowerCase());
            }
          case 149: break;
          case 73: 
            { return new Symbol(symsG.continuar, yycolumn, yyline, yytext().toLowerCase());
            }
          case 150: break;
          case 74: 
            { return new Symbol(symsG.protegido, yycolumn, yyline, yytext().toLowerCase());
            }
          case 151: break;
          case 75: 
            { return new Symbol(symsG.seleccion, yycolumn, yyline, yytext().toLowerCase());
            }
          case 152: break;
          case 76: 
            { return new Symbol(symsG.incluirhk, yycolumn, yyline, yytext().toLowerCase());
            }
          case 153: break;
          case 77: 
            { return new Symbol(symsG.graphikarfuncion, yycolumn, yyline, yytext().toLowerCase());
            }
          case 154: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
